districts = {
    "Göteborg": 7,
    "Blekinge": 2,
    "Dalsland": 3,
    "Jämtland/Härjedalen": 10,
    "Skåne": 14,
    "Södermanland": 17,
    "Västerbotten": 20,
    "Ångermanland": 23,
    "Bohuslän": 25,
    "Gestrikland": 6,
    "Halland": 8,
    "Medelpad": 11,
    "Småland": 15,
    "Uppland": 18,
    "Västergötland": 21,
    "Örebro län": 13,
    "Gotland": 5,
    "Hälsingland": 9,
    "Norrbotten": 12,
    "Stockholm": 16,
    "Västmanland": 22,
    "Östergötland": 24,
}
